# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJ1BW34wFWiT1iy7n0JvuZmaGlzfOVT1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/titanic-training-data.csv")
df.head(10)

df.shape

df.info

df.dtypes

df.isnull().sum()

df.describe()

sns.relplot(x="Age",y="Fare",data=df)

sns.relplot(x="Age",y="Fare",hue="Sex",data=df)

sns.catplot(x="Age",y="Fare",hue="Sex",data=df)

df.head(10)

sns.catplot(x="Sex",y="Age",data=df)

df2 = pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/titanic-training-data.csv")

df2.head()

sns.catplot(x="Age", y="Fare", data=df2)

sns.catplot(x="Age", y="Fare",hue="Sex",jitter=False, data=df2)

sns.catplot(x="Age", y="Fare",kind="swarm", data=df2)

sns.catplot(x="Age", y="Fare",kind="box", data=df2)

sns.catplot(x="Age", y="Fare",kind="violin", data=df2)

sns.catplot(x="Age", y="Fare",kind="violin",split=True, data=df2)

sns.catplot(x="Age", y="Fare",hue="Sex",kind="bar", data=df2)

sns.catplot(x="Age", y="Fare",hue="Sex",kind="point", data=df2)

sns.distplot(df2.Age)

sns.distplot(df2.Age, kde=False, rug = True)

sns.jointplot(x="Age", y="Fare", data=df2)

sns.jointplot(x="Age", y="Fare", data=df2, kind="kde");

corrmat = df2.corr()
f, ax = plt.subplots(figsize=(9, 6))
sns.heatmap(corrmat, vmax=.8, square=True)

